select * from empleado;
select * from departamento;
select distinct nombre_depto from departamento;
select nombre, salario from empleado order by nombre asc;
select distinct comision from empleado;
select * from empleado where cargo = "Secretaria";
select * from empleado where cargo = "Vendedor" order by nombre asc;
select nombre, cargo from empleado order by salario asc;
select nombre as Nombre, cargo as Cargo from empleado order by salario asc;
select salario, comision from empleado where id_depto = 2000 order by comision asc;
select (salario + comision + 500) as Valor_A_Pagar from empleado where id_depto = 3000 order by nombre asc;
select nombre from empleado where nombre like "J%";
select salario, comision, (salario + comision) as salario_total, nombre from empleado where comision > 1000;
select salario, comision, (salario + comision) as salario_total, nombre from empleado where !comision;
select nombre from empleado where comision > salario;
select nombre,comision, salario from empleado where comision <= (0.3 * salario);
select nombre from empleado where !(nombre like "%ma%");
select nombre_depto from departamento where nombre_depto in ("Ventas","Investigacion","Mantenimiento");
select nombre_depto from departamento where !(nombre_depto in ("Ventas","Investigacion","Mantenimiento"));
select max(salario) from empleado;
select nombre from empleado order by nombre desc limit 1;
select max(salario), min(salario), (max(salario) - min(salario)) as diferencia from empleado;
select id_depto, avg(salario) from empleado group by id_depto;
select id_depto, count(id_depto) as cantidad_empleados from empleado group by id_depto having count(id_depto)>3;
select cod_jefe, nombre, count(id_empleado) from empleado group by cod_jefe having count(id_empleado)>=2;
select d.nombre_depto from departamento d left join empleado e on d.id_depto=e.id_depto group by e.id_depto having  count(e.id_depto)=0;
select nombre, salario from empleado where salario >= (select avg(salario) from empleado) group by id_depto;